### PR TITLE
report method has been modified to accept ajaxOption object containin…

### PR DESCRIPTION
**Pull request by raminbp**
a new parameter has been added to report method called ajaxOptions, if the object contains a headers property the headers will be added to the request headers. 

eg: 

``` js
{
  headers: {
      'Authorization' : 'token'
  }
}
```

The report method adds the "Authorization" header to the request.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Looks nice :+1:

**Comment by raminbp** [comment]
Thank you, it helps a lot on Restful APIs

**Comment by eriwen** [comment]
This implementation looks good. I've love to merge this if you wouldn't mind adding a unit test and updating the README to add the optional argument to `StackTrace.report()`. Let us know if we can help with testing.

**Comment by raminbp** [comment]
yes, it would be great.

**Comment by eriwen** [comment]
This change was implemented by https://github.com/stacktracejs/stacktrace.js/commit/2e8dbc2b41408af5a941270b2e1e8612b5a89261 — closing as superseded. Thank you @raminbp.

**Pull request closed without merging**
